name: tetrica-tasks workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка зависимостей
        pip install -r requirements.txt
    - name: Run unittests
      run: |
        # запуск юниттестов
        python -m unittest
    - name: Test tasks with flake8 and mypy
      run: |
        # запуск проверки проекта по flake8
        flake8 tasks/task1.py tasks/task2.py tasks/task3.py
        # запуск проверки проекта по mypy
        mypy tasks/task1.py tasks/task2.py tasks/task3.py
    - name: Test tests with flake8
      run: |
        # запуск проверки проекта по flake8
        flake8 tests/test1.py tests/test2.py tests/test3.py
  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!